version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      astro-and-typescript:
        patterns:
          - "astro"
          - "@astrojs/*"
          - "typescript"
          - "@types/*"
